[project]
name = "shapepackingppo"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "tensordict>=0.10.0",
    "torch>=2.10.0",
    "torchrl>=0.10.1",
]
